### ISSUE TITLE
`CommandID` fields are not needed in the Builders

### ISSUE THREAD

**Issue by itsyaasir** [collinsmuriuki/mpesa-rust#45]
Each API has `CommandID` field which are filled with that certain API request you're doing. While it's optional to fill it, I just don't see the need to have it since it Errors out if the client inputs any other `CommandID` other than required one.
I suggest we get rid of `CommandID` setter and fill with the respective `CommandID`'s in the respective API.

**Comment by itsyaasir** [comment]
What do you think @collinsmuriuki ?

**Comment by collinsmuriuki** [comment]
Mmmh, not too sure about this, we don't have much control over the API, Safaricom might make it possible to use other command ids for the same API. Perhaps we could mark the methods as `#[depreciated]` though, and document a warning to the user

**Comment by itsyaasir** [comment]
Yeah true, we don't really control the API. I don't think we wanna mark it as `#[deprecated]`.
