### ISSUE TITLE
MIgrate to `dotenvy`

### ISSUE THREAD

**Issue by itsyaasir** [collinsmuriuki/mpesa-rust#46]
`dotenv` crate is no longer maintained, best alternative suggested is `dotenvy` which is fork of the original crate `dotenv`.
See this [issue](https://github.com/collinsmuriuki/mpesa-rust/issues/43)

**Comment by collinsmuriuki** [comment]
@crispinkoech interested in working on this?

**Comment by crispinkoech** [comment]
Sure 👍

**Comment by collinsmuriuki** [comment]
@crispinkoech unassigning you since @itsyaasir is already working on this on #59

**Comment by collinsmuriuki** [comment]
Also closed since this is a duplicate of #43

**Comment by crispinkoech** [comment]
No worries 👍
