### ISSUE TITLE
Early `Error` return if a required param is missing

### ISSUE THREAD

**Issue by itsyaasir** [collinsmuriuki/mpesa-rust#47]
Currently we don’t have any protection against sending an empty required field. We have to return early error.
Take a look at `transaction_reversal.rs` file and see how it’s implemented. We need to add a new `Error` type.

**Comment by collinsmuriuki** [comment]
I think with this implemented, this TODO comment will be addressed

https://github.com/collinsmuriuki/mpesa-rust/blob/master/src/services/b2b.rs#L231

**Comment by collinsmuriuki** [comment]
Closing since this has already been addressed by #60
