### ISSUE TITLE
Implement Bill Manager API

### ISSUE THREAD

**Issue by itsyaasir** [collinsmuriuki/mpesa-rust#57]

**Comment by collinsmuriuki** [comment]
@crispinkoech another one that might be of interest to you

**Comment by crispinkoech** [comment]
This ones looks like a good one to start off with :)

**Comment by crispinkoech** [comment]
@itsyaasir is this something you'd require/want urgently? If it isn't, I'll take it up and build it slowly in my free time :)

**Comment by itsyaasir** [comment]
No problem @crispinkoech
