### ISSUE TITLE
Test failure.

### ISSUE THREAD

**Issue by Borwe** [collinsmuriuki/mpesa-rust#74]
This test fails,  [test_client_will_not_authenticate_with_sandbox_credentials_in_production](https://github.com/collinsmuriuki/mpesa-rust/blob/ad79f58381a3bb9c447cb98c1c66c13b6b8602e2/tests/mpesa-rust/helpers.rs#L101) it asserts true, when it should assert false on some secrets and key combos.

I suspect that some combos are actually used by Safaricom in production, like mine were which I just created an account on sandbox today. Possible solution? Remove test all together.
![image](https://github.com/collinsmuriuki/mpesa-rust/assets/3319843/f0789227-0afa-4958-8336-867efd7c8bf5)

**Comment by collinsmuriuki** [comment]
Strange, this test should probably be removed due to it's flaky nature. I had actually removed reliance on safaricom's unreliable sandbox env for testing, this was the only test that survived the purge.

**Comment by collinsmuriuki** [comment]
Good catch though, feel free to create a PR for this

**Comment by Borwe** [comment]
PR created :+1:
